spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/
    register-with-eureka: false
    fetch-registry: false
  #  instance:
  #    preferIpAddress: true
  server:
    # 关闭自我保护模式（缺省为打开）
    enable-self-preservation: false
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix: INFO

server:
  port: 10010